name: ANALISIS_CALIDAD_UCV

on:
  push:
    branches:
      - developer
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
uses: SonarSource/sonarcloud-github-action@6a975122c6671141e9d76d6c3c9b6ddf3a27bf04       
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
